* Scramble a file

You are required to create two utilities; scramble.c and unscramble.c that are called by command line specifying the name of the file to scramble/unscramble. 

For example: 
C:> scramble myfile.txt 
C:> unscramble myfile.txt.sbl 

The scramble utility reads a file (any type of file) and generates a new file with the same name as the input file but with the extension .sbl added to the end of the file (keep the previous extension, for instance picture.bmp becomes picture.bmp.sbl). The .sbl file is generated by swapping bytes two by two. For instance, the 1stbyte is swapped with the 2nd, the 3rd with the 4th and so on.. 

*** for in put for an input like

| byte 1 | byte 2 | byte 3 | ... | byte n-1 | byte n   |
|--------+--------+--------+-----+----------+----------|
| byte 2 | byte 1 | byte 4 | ... | byte n   | byte n-1 |


If the input file has an odd number of bytes the last one will not be swapped. The scramble utility encrypts a file so that it cannot be read anymore by the right application. The utility unscramble does the reverse task: it takes a scrambled file.sbl and recreate the original file by removing the .sbl extension from the name and reswapping back the bytes. Try the program with any type of file and check if, by scrambling and unscrambling a file, the resulting file is the same as the original starting file. 
