#!/usr/bin/env python3

import csv
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("file",help="the name of the file to work with.",type=str)
parser.add_argument("col", help="column index to use for comparaison.",type=int)
parser.add_argument('cut', help="number to make the cut from.",type=int)

args = parser.parse_args()

data = []
with open(args.file, 'r') as csvfile:
	reader = csv.reader(csvfile,delimiter=',')
	has_header = csv.Sniffer().has_header(csvfile.read(512))
	csvfile.seek(0)

	if has_header : headers = next(reader)
	
	for row in reader:
		try:
			r = []
			r.append(row[0])
			r.extend(map(int,row[1:(len(row) -1)]))
			if len(r) < len(headers) : r.extend(row[len(row)-1:])
			data.append(r)
		except ValueError:
			raise

filtered = filter(lambda x: x[args.col] >= args.cut, data)

def pretty(iterable):
	for i in iterable:
		print(i, end='\t')
	print()
	
if __name__=='__main__':
	pretty(headers)
	for i in filtered :
		pretty(i)
